---

- name: Group host for vars
  hosts: localhost
  gather_facts: False
  tasks:
  - add_host:
      host: localhost
      groups: issue59004

- import_playbook: gcpinstance.yml

- name: Can't install package Failed to validate the SSL certificate
  hosts: distro_Ubuntu

  roles:
  - issue59004

